尝试修了一些自己发现的问题
MaaAssistantArknights/MaaX pull request #129
Opened 2023-04-24 09:54 UTC by interfacew

那个切设备的改法还是有点太蠢了
相当于是直接新开了个页面然后两个轮流换
好像是router去push自己会不刷新
等一个佬（

2023-04-24 13:57 UTC, ChingCdesu commented on packages/renderer/src/store/devices.ts
但地址有可能是随机端口，如果是随机端口怎么解决显示的问题

2023-04-24 13:58 UTC, ChingCdesu commented on packages/renderer/src/router/index.ts
直接在Task.vue上面修改，这样我没办法比较你修改了啥

2023-04-24 14:09 UTC, ChingCdesu requested changes
将Task2合并到Task吧，这样看起来方便点，合并完了再看下

2023-04-24 14:09 UTC, ChingCdesu commented on packages/renderer/src/components/Task/NewTask.vue
> +        <div v-if="!props.isCollapsed" style="width :100%" class="card-header" />
修改后无法正确显示创建新任务的下拉框

2023-04-24 17:08 UTC, interfacew commented
这个task左边设备显示的我也不知道能怎么修
我之前的方案是直接新开了一个本质和task一样的task2页面
然后task1去task2，task2回到task1，这样确实是不会出现显示错误了
但是很难看而且到时候修改task会很麻烦
有没有大佬会整啊orz

2023-04-24 17:09 UTC, interfacew commented
顺带一提如果router里只是加一个页面用同一个sidebar和main不解决问题
估计是缓存导致的

2023-04-25 14:36 UTC, interfacew commented
把左边设备切换修好了（

2023-04-27 01:56 UTC, ChingCdesu reviewed
因为存在force-push，pr可能不会被合并

2023-04-27 01:56 UTC, ChingCdesu commented on packages/renderer/src/components/Device/DeviceCard.vue
> +let routeUuid = computed(
computed不应该被再次赋值

2023-04-27 01:56 UTC, ChingCdesu commented on packages/renderer/src/components/Device/DeviceDetailPopover.vue
> +const tempName = ref('')
tempName不应该作为传入template中的对象名，更换一个更加直观的名字

2023-04-27 01:56 UTC, ChingCdesu commented on packages/renderer/src/components/Device/DeviceDetailPopover.vue
> +            @change="updateDisplayName"
`@change`事件需要有属性`passively-activated`

2023-04-27 01:56 UTC, ChingCdesu commented on packages/renderer/src/layouts/pages/Task.vue
> +let uuid = computed(() => router.currentRoute.value.params.uuid as string)
computed不应该被重新赋值

2023-04-27 01:56 UTC, ChingCdesu commented on packages/renderer/src/store/initial.ts
> +export async function initialStor(): Promise<void> {
异常修改

2023-04-27 01:57 UTC, ChingCdesu commented on packages/renderer/src/components/Device/DeviceDetailPopover.vue
> +            @change="updateDisplayName"
https://www.naiveui.com/zh-CN/dark/components/input#passively-activated.vue

2023-04-27 14:40 UTC, closed without merging